[package]
name = "ast_reflection"
version = "0.1.0"
edition = "2021"
include = ["Cargo.toml", "src/**/*.rs"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1"
swc_common = "*"
swc_ecma_ast = "^0.87.0"
swc_ecma_transforms_base = "*"
swc_ecma_transforms_typescript = "*"
swc_ecma_visit = "*"
swc_plugin = "*"
im = "*"
strum = "0.24"
strum_macros = "0.24"

[dev-dependencies]
swc_ecma_parser = "0.112.2"
swc_ecma_transforms_testing = "0.100.0"
testing = "0.26.0"