[package]
name = "nodejs_closure_serializer"
version = "0.1.0"
edition = "2021"
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
serde = "1"
swc_common = "*"
swc_ecma_transforms_base = "*"
swc_ecma_transforms_typescript = "*"
swc_ecma_visit = "*"
swc_plugin = "*"
im = "*"

[dev-dependencies]
swc_ecma_parser = "0.111.0"
swc_ecma_transforms_testing = "0.99.0"
testing = "0.25.0"